language: ruby

before_script: 
  - curl -sSL https://raw.githubusercontent.com/moliware/travis-solr/master/travis-solr.sh | SOLR_VERSION=4.8.1 bash
  - mysql -e 'create database uniiv_test;'
  - bundle exec rails g uniiv:secret
  - RAILS_ENV=test bundle exec rake sunspot:solr:start

after_script:
  - RAILS_ENV=test bundle exec rake sunspot:solr:stop

rvm:
  - '2.0.0'
  - '2.1.0'

gemfile:
  - Gemfile

matrix:

notifications:
  email: false
