language: ruby

before_script: 
  - curl -sSL https://raw.githubusercontent.com/moliware/travis-solr/master/travis-solr.sh | SOLR_VERSION=4.8.1 bash
  - mysql -e 'create database uniiv_test;'
  
rvm:
  - '2.0.0'
  - '2.1.0'
  - 'rbx-2'

gemfile:
  - Gemfile

matrix:

notifications:
  email: false
