production:
  solr:
    hostname: localhost
    port: 8080
    log_level: WARNING
    path: /solr/production
    pid_dir: '/var/run'
    pid_dir: '/var/run'

development_server:
  solr:
    hostname: localhost
    port: 8080
    log_level: WARNING
    path: /solr/development_server
    pid_dir: '/var/run'
    pid_dir: '/var/run'

development:
  solr:
    hostname: localhost
    port: 8982
    log_level: INFO
    path: /solr/development

test:
  solr:
    hostname: localhost
    port: 8981
    log_level: WARNING
    path: /solr/test
    
